import { Montserrat_Alternates } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

import { SessionProvider } from "next-auth/react";

const montserrat = Montserrat_Alternates({
  subsets: ["latin"],
  weight: ["100", "400", "700"],
  display: "swap", // prevents flashing
});

export const metadata = {
  title: "OrganiseMe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} backdrop-blur-3xl bg-[#0a0a0a]`}
      >
        <SessionProvider>
          <Navbar />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
